In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
legislators_file = "Resources/legislators-current-terms.csv"
legislators_df = pd.read_csv(legislators_file)
legislators_df.head()

,address,bioguide,caucus,chamber,class,contact_form,district,end,fax,last,...,party_affiliations,phone,relation,rss_url,start,state,state_rank,title,type,url
0,NaN,B000944,NaN,NaN,NaN,NaN,13.0,1995-01-03,NaN,NaN,...,NaN,NaN,NaN,NaN,1993-01-05,OH,NaN,NaN,rep,NaN
1,NaN,B000944,NaN,NaN,NaN,NaN,13.0,1997-01-03,NaN,NaN,...,NaN,NaN,NaN,NaN,1995-01-04,OH,NaN,NaN,rep,NaN
2,NaN,B000944,NaN,NaN,NaN,NaN,13.0,1999-01-03,NaN,NaN,...,NaN,NaN,NaN,NaN,1997-01-07,OH,NaN,NaN,rep,NaN
3,NaN,B000944,NaN,NaN,NaN,NaN,13.0,2001-01-03,NaN,NaN,...,NaN,NaN,NaN,NaN,1999-01-06,OH,NaN,NaN,rep,NaN
4,NaN,B000944,NaN,NaN,NaN,NaN,13.0,2003-01-03,NaN,NaN,...,NaN,NaN,NaN,NaN,2001-01-03,OH,NaN,NaN,rep,NaN

In [8]:
no_health_ins_file = "Resources/Population_Without_Health_Insurance_Coverage_State_2013-2015.csv"
no_health_ins_df = pd.read_csv(no_health_ins_file)
no_health_ins_df.head()

,State,Medicaid Expansion State? Yes (Y) or No (N)1,2013 Uninsured - Number in thousands,2013 Uninsured - Number - Margin of Error2 (±),2013 Uninsured - Percent,2013 Uninsured - Percent - Margin of Error2 (±),2014 Uninsured - Number,2014 Uninsured - Number - Margin of Error2 (±),2014 Uninsured - Percent,2014 Uninsured - Percent - Margin of Error2 (±),...,2015 Uninsured - Percent,2015 Uninsured - Percent - Margin of Error2 (±),Difference in Uninsured (2015 less 2014) - Number,Difference in Uninsured (2015 less 2014) - Number - Margin of Error2 (±),Difference in Uninsured (2015 less 2014) - Percent,Difference in Uninsured (2015 less 2014) - Percent - Margin of Error2 (±),Difference in Uninsured (2015 less 2013) - Number,Difference in Uninsured (2015 less 2013) - Number - Margin of Error2 (±),Difference in Uninsured (2015 less 2013) - Percent,Difference in Uninsured (2015 less 2013)- Percent - Margin of Error2 (±)
0,United States,NaN,"45,181",200,14.5,0.1,"36,670",190,11.7,0.1,...,9.4,0.1,"*-6,913",261,*-2.3,0.1,"*-15,423",269,*-5.1,0.1
1,Alabama,N,645,17,13.6,0.4,579,17,12.1,0.4,...,10.1,0.3,*-95,23,*-2.0,0.5,*-161,23,*-3.4,0.5
2,Alaska,N,132,7,18.5,1.0,122,6,17.2,0.9,...,14.9,0.7,*-16,8,*-2.3,1.1,*-26,9,*-3.7,1.2
3,Arizona,Y,"1,118",24,17.1,0.4,903,18,13.6,0.3,...,10.8,0.3,*-175,28,*-2.8,0.4,*-390,32,*-6.3,0.5
4,Arkansas,Y,465,14,16.0,0.5,343,13,11.8,0.4,...,9.5,0.4,*-66,18,*-2.3,0.6,*-187,18,*-6.5,0.6